title: <h1 style="color:teal;"> // Cody Le </h1> # your name (or website title) here
logo: "/images/ProfilePhoto2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b> Data Centric Creative Problem Solver // </b>
  Learner, Evaluative Thinker,       
  Coffee & Cold Brewer  
  <br><br>
  Current graduate student pursuing a M.S. in Data Science at
  DePaul University - College of Computing & Digital Media. <br><br>
  <a href="mailto: lacodyle@gmail.com"><img src="https://img.shields.io/badge/-Email-68edc5?logo=google"/> </a> 
  <a href="pdf/CodyLe-Resume.pdf"><img src="https://img.shields.io/badge/-Resume-0cab90?logo=adobe"/></a> 
  <a href="https://www.linkedin.com/in/lacodyle/"><img src="https://img.shields.io/badge/-LinkedIn-0072b1?logo=linkedin"/></a>  
  
  
theme: jekyll-theme-minimal
google_analytics: G-N027R485VG # your Google Analytics tracking ID here
