title: <h1 style="color:teal;"> Cody Le </h1> # your name (or website title) here
logo: "/images/ProfilePhoto2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b> Data Centric Creative Problem Solver // </b>
  Learner, Evaluative Thinker,       
  Coffee & Cold Brewer  
  <br><br>
  Current graduate student pursuing a M.S. in Data Science at
  DePaul University - College of Computing & Digital Media. <br><br>
  <a href="https://www.linkedin.com/in/lacodyle/">LinkedIn</a> // 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
