title: Cody Le # your name (or website title) here
logo: "/images/ProfilePhoto1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Centric Creative Problem Solver
  <br><br>
  Learner, Evaluative Thinker, Cold Brewer 
  <br><br>
  <a href="https://www.linkedin.com/in/lacodyle/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
