title: <h1 style="color:teal;"> Cody Le // </h1> # your name (or website title) here
logo: "/images/PorfolioPhoto3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b> Data Centric Creative Problem Solver // </b>
  Learner, Evaluative Thinker,       
  Cold Coffee Brewer  
  <br><br>
  Recent alumnus from Jarvis College of Computing & Digital Media, DePaul University. //
  M.S. in Data Science with Distinction. <br><br>
  <a href="mailto: lacodyle@gmail.com"><img src="https://img.shields.io/badge/-Email-68edc5?logo=google"/> </a> 
  <a href="pdf/CodyLe-Resume2023.pdf" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/badge/-Resume-0cab90?logo=adobe"/></a> 
  <a href="https://www.linkedin.com/in/lacodyle/" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/badge/-LinkedIn-0072b1?logo=linkedin"/></a>
  <a href="https://github.com/lacodyle" target="_blank" rel="noopener noreferrer"> <img src="https://img.shields.io/badge/-GitHub-3514c9?logo=github"/></a>
  
  
theme: jekyll-theme-minimal
google_analytics: G-N027R485VG # your Google Analytics tracking ID here
